name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15  

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Haskell Tools (GHC, Cabal, Stack)
      run: |
        # Para macOS
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew update
          brew install haskell-stack
        else
          # Para Ubuntu
          sudo apt-get update
          sudo apt-get install -y haskell-stack
        fi

        # Atualiza o Stack para a versão mais recente
        stack upgrade --force-download

        # Instala a versão mais recente do GHC e Cabal
        stack setup --resolver lts

        # Verificação das versões instaladas
        stack exec -- ghc --version
        stack exec -- cabal --version
        stack --version

    - name: Build project
      run: stack build

    - name: Run tests
      run: stack test
