name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20  # Aumentado o tempo limite para evitar cancelamento precoce

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Haskell Tools (GHC, Cabal, Stack)
      run: |
        # Para macOS
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew update
          brew install haskell-stack cabal-install
        else
          # Para Ubuntu
          sudo apt-get update
          sudo apt-get install -y haskell-stack cabal-install
        fi

        # Atualiza o Stack para a versão mais recente
        stack upgrade --force-download

        # Verificação das versões instaladas (caso o programa não esteja instalado será lançado um erro)
        ghc --version
        cabal --version
        stack --version
        cabal install hlint

    - name: Build project
      run: stack build

    - name: Run tests
      run: hlint . && stack test
