name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15  

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.7'         
        cabal-version: '3.8.1.0'     
        enable-stack: true           

    - name: Verify Haskell Tools
      run: |
        ghc --version
        cabal --version
        stack --version

    - name: Build project
      run: make build

    - name: Run tests
      run: make test
