name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10  # Reduzindo pois a execução será mais rápida

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Cache cabal packages
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Cache stack packages
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install Haskell Tools (GHC, Cabal, Stack)
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew update && brew install haskell-stack cabal-install
        else
          sudo apt-get update && sudo apt-get install -y haskell-stack cabal-install
        fi

        ghc --version
        cabal --version
        stack --version
        cabal update
        cabal install hlint

    - name: Build project
      run: stack build

    - name: Run HLint
      run: hlint .

    - name: Run tests
      run: stack test
