name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install GHC, Cabal, and Stack
      run: |
        if [[ "${{ matrix.os }}" == "macOS" ]]; then
          brew install ghc cabal-install haskell-stack
        else
          sudo apt-get update && sudo apt-get install -y ghc cabal-install haskell-stack
        fi
        ghc --version
        cabal --version
        stack --version

    - name: Build project
      run: make build

    - name: Run tests
      run: make test
